name: Mirror and run GitLab CI

on:
  schedule:
    - cron: "0 0,8,16 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Mirror + trigger CI
        if: github.event_name == 'schedule'
        uses: SvanBoxel/gitlab-mirror-and-ci-action@master
        with:
          args: "https://gitlab.com/hardi.kakalaw/toys_devops.git"
        env:
          FOLLOW_TAGS: "false"
          FORCE_PUSH: "false"
          GITLAB_HOSTNAME: "gitlab.com"
          GITLAB_USERNAME: "hardi.kakalaw"
          GITLAB_PASSWORD: "glpat-UQWHkL5nw9VAo9pgd6Jd"
          GITLAB_PROJECT_ID: "46116784"
          GITHUB_TOKEN: "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"
