name: Mirror and push to GitLab

on:
  push:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Push to GitLab
        uses: actions/github-script@v4
        env:
          GITLAB_TOKEN: "glpat-H-U7CzCevMM9BxoEoRxN"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const git = require('isomorphic-git');
            const http = require('isomorphic-git/http/node');
            const fs = require('fs');
            
            const gitlabToken = process.env.GITLAB_TOKEN;
            const gitlabRepo = 'https://gitlab.com/hardi.kakalaw/toys_devops';
            const gitlabBranch = 'development';

            async function main() {
              await git.clone({
                fs,
                http,
                dir: '.',
                url: gitlabRepo,
                singleBranch: true,
                depth: 1,
                ref: gitlabBranch,
                username: 'hardi.kakalaw',
                password: gitlabToken,
              });

              await git.add({
                fs,
                dir: '.',
                filepath: 'path/to/modified/files',
              });

              await git.commit({
                fs,
                dir: '.',
                author: {
                  name: 'Hardi',
                  email: 'hardi.kakalaw@chasacademy.se',
                },
                message: 'Commit message',
              });

              await git.push({
                fs,
                http,
                dir: '.',
                remote: 'origin',
                ref: gitlabBranch,
                username: 'hardi.kakalaw',
                password: gitlabToken,
              });
            }

            main();
