name: Mirror and run GitLab CI

on:
  push:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Merge changes from remote
        run: git pull origin development

      - name: Push changes to GitLab
        run: |
          git remote add gitlab https://gitlab.com/hardi.kakalaw/toys_devops.git
          git push gitlab development

env:
  GITLAB_HOSTNAME: gitlab.com
  GITLAB_USERNAME: hardi.kakalaw
  GITLAB_PASSWORD: "glpat-UQWHkL5nw9VAo9pgd6Jd"
  GITLAB_PROJECT_ID: 46116784
