name: Mirror and run GitLab CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Mirror + trigger CI
      uses: SvanBoxel/gitlab-mirror-and-ci-action@master
      with:
        args: "https://gitlab.com/hardi.kakalaw/toys_devops development"
      env:
        FOLLOW_TAGS: "false"
        FORCE_PUSH: "false"
        GITLAB_HOSTNAME: "gitlab.com"
        GITLAB_USERNAME: "hardi.kakalaw"
        GITLAB_PASSWORD: "glpat-H-U7CzCevMM9BxoEoRxN"
        GITLAB_PROJECT_ID: "46116784"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
