name: Sync to GitLab

on:
  push:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Push changes to GitLab
        run: |
          git remote add gitlab https://gitlab.com/hardi.kakalaw/toys_project.git
          git config --global user.email "hardi.kakalaw@chasacademy.se"
          git config --global user.name "hardi.kakalaw"
          git push gitlab development

      - name: Trigger GitLab pipeline
        run: |
          curl --request POST --header "Content-Type: application/json" --header "PRIVATE-TOKEN: glpat-AyZEPSitid1f7UWyksYS" --data "{\"ref\":\"development\"}" "https://gitlab.com/api/v4/projects/45703278/pipeline"
