name: Gitlab Sync

on:
  push:
    branches:
      - development

jobs:
  sync:
    name: Gitlab Sync
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: action-pack/gitlab-sync@v3
        with:
          url: https://gitlab.com/hardi.kakalaw/toys_project.git
          username: ${{ github.actor }}
          token: ${{ secrets.GITLAB_TOKEN }}
