name: Mirror and run GitLab CI

on:
  push:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Push to GitLab
        run: git push --force --quiet "https://gitlab.com/hardi.kakalaw/toys_project.git" HEAD:development

      - name: Trigger GitLab pipeline
        run: curl --request POST --header "PRIVATE-TOKEN: ${{ secrets.GITLAB_TOKEN }}" "https://gitlab.com/api/v4/projects/45703278/pipeline"
