name: Sync to GitLab

on:
  push:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Push changes to GitLab
        uses: actions/github-script@v4
        with:
          script: |
            git remote add gitlab https://gitlab.com/hardi.kakalaw/toys_project.git
            git config --global user.email "hardi.kakalaw@chasacademy.se"
            git config --global user.name "hardi.kakalaw"
            git push gitlab development
          repository: https://gitlab.com/hardi.kakalaw/toys_project.git

      - name: Trigger GitLab pipeline
        uses: appleboy/gitlab-ci-action@v2
        with:
          gitlab_url: https://gitlab.com/
          ref: development
          token: "glpat-AyZEPSitid1f7UWyksYS"
