name: Mirror and run GitLab CI

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Push to GitLab
        run: |
          git remote add gitlab https://gitlab.com/hardi.kakalaw/toys_project.git
          git push gitlab HEAD:development

      - name: Trigger GitLab pipeline
        uses: dawidd6/action-gitlab-pipeline@v4
        with:
          gitlab_url: 'https://gitlab.com'
          project_id: '45703278'
          ref: 'development'
          token: "tvzXz3zHo_dyczuoMnAu"
