name: Push to GitLab

on:
  push:
    branches:
      - development

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Push changes to GitLab
        uses: git-actions/git-push@v1
        with:
          branch: development
          remote_repository: 'git@gitlab.com:hardi.kakalaw/toys_project.git'
          force: true
          ssh_private_key: ${{ env.GITLAB_SSH_PRIVATE_KEY }}

      - name: Trigger pipeline in GitLab
        uses: crazy-max/ghaction-gitlab-ci@v2
        with:
          url: 'https://gitlab.com'
          api_token: "glpat-iRaN7gRzRud1NcXWXnC7"
          project_id: '45703278'

