name: Mirror and run GitLab CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install ssh client
      run: sudo apt-get install openssh-client
    - name: Mirror to GitLab and run GitLab CI
      uses: SvanBoxel/gitlab-mirror-and-ci-action@0.2
      with:
        args: "ssh://git@gitlab.com:22/hardi.kakalaw/toys_project.git"
      env:
        FOLLOW_TAGS: "false"
        FORCE_PUSH: "false"
        GITLAB_HOSTNAME: "gitlab.com"
        GITLAB_USERNAME: "hardi.kakalaw"
        GITLAB_PASSWORD: "ALMD8vEkzpg5szy7SB3y"
        GITLAB_PROJECT_ID: "45703278"
        GITHUB_TOKEN: "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"
