name: Sync to GitLab

on:
  schedule:
    - cron: "8 19 * * *"

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up GitLab remote
        run: |
          git remote add gitlab https://gitlab.com/hardi.kakalaw/toys_devops.git
          git config --global user.email "hardi.kakalaw@chasacademy.se"
          git config --global user.name "hardi.kakalaw"
          git remote -v

      - name: Add changes to staging
        run: git add .

      - name: Commit changes
        run: git commit -m "Daily push from GitHub"

      - name: Push to GitLab
        run: git push gitlab development
